const GTM_KEYWORDS = [
  "sales",
  "account executive",
  "account exec",
  "\\bae\\b",
  "sdr",
  "bdr",
  "business development",
  "marketing",
  "demand gen",
  "growth",
  "revenue",
  "revops",
  "\\bgtm\\b",
  "partnerships",
  "customer success",
  "cs manager",
];

const EXCLUDE_KEYWORDS = ["point of sale", "salesforce developer", "salesforce admin", "salesforce engineer"];

// Flagged separately rather than excluded — a real GTM-adjacent role, not a false positive.
const SALES_ENGINEER_RE = /sales engineer/i;

const LEADERSHIP_RE = /\b(vp|vice president|head of|director|cro|cmo)\b/i;

function matchesAny(text: string, patterns: string[]): boolean {
  return patterns.some((p) => new RegExp(p, "i").test(text));
}

export function isGtmRole(title: string, department: string | null): boolean {
  const haystack = `${title} ${department ?? ""}`;
  if (matchesAny(haystack, EXCLUDE_KEYWORDS)) return false;
  return matchesAny(haystack, GTM_KEYWORDS);
}

export function isSalesEngineerRole(title: string): boolean {
  return SALES_ENGINEER_RE.test(title);
}

export function isLeadershipGtmRole(title: string): boolean {
  return LEADERSHIP_RE.test(title) && matchesAny(title, GTM_KEYWORDS);
}

/** Kill switch — flip to false to restore all-locations GTM monitoring. */
export const GTM_US_ONLY = true;

/**
 * True if TEXT (title, department, or anything else) mentions a non-US country/region —
 * a defense-in-depth check independent of the location-string classification below. A role
 * titled "Head of BD, Eastern Europe (Poland/Hungary)" should be excluded even if its bare
 * location field happens to be a city name that collides with a small US town (e.g. "Warsaw").
 */
export function hasNonUsRegionMarker(text: string): boolean {
  return matchesAny(text.toLowerCase(), NON_US_COUNTRY_REGION_MARKERS);
}

export const NON_US_COUNTRY_REGION_MARKERS = [
  "united kingdom",
  "\\buk\\b",
  "england",
  "scotland",
  "wales",
  "ireland",
  "canada",
  "germany",
  "france",
  "spain",
  "italy",
  "netherlands",
  "poland",
  "portugal",
  "sweden",
  "switzerland",
  "india",
  "singapore",
  "australia",
  "japan",
  "china",
  "hong kong",
  "brazil",
  "mexico",
  "argentina",
  "israel",
  "united arab emirates",
  "\\buae\\b",
  "saudi",
  "qatar",
  "\\bemea\\b",
  "\\bapac\\b",
  "\\blatam\\b",
  "middle east",
  "\\beurope\\b",
  "\\basia\\b",
  "eastern europe",
  "nato",
];

const US_STATE_NAMES = [
  "alabama", "alaska", "arizona", "arkansas", "california", "colorado", "connecticut",
  "delaware", "florida", "georgia", "hawaii", "idaho", "illinois", "indiana", "iowa",
  "kansas", "kentucky", "louisiana", "maine", "maryland", "massachusetts", "michigan",
  "minnesota", "mississippi", "missouri", "montana", "nebraska", "nevada",
  "new hampshire", "new jersey", "new mexico", "new york", "north carolina",
  "north dakota", "ohio", "oklahoma", "oregon", "pennsylvania", "rhode island",
  "south carolina", "south dakota", "tennessee", "texas", "utah", "vermont",
  "virginia", "washington", "west virginia", "wisconsin", "wyoming",
  "district of columbia", "washington dc",
];

const US_STATE_ABBR_RE =
  /(^|[,\s])(al|ak|az|ar|ca|co|ct|de|fl|ga|hi|id|il|in|ia|ks|ky|la|me|md|ma|mi|mn|ms|mo|mt|ne|nv|nh|nj|nm|ny|nc|nd|oh|ok|or|pa|ri|sc|sd|tn|tx|ut|vt|va|wa|wv|wi|wy|dc)([,\s]|$)/i;

const NON_US_CITY_MARKERS = [
  "london",
  "dublin",
  "toronto",
  "vancouver",
  "berlin",
  "munich",
  "paris",
  "madrid",
  "barcelona",
  "amsterdam",
  "bangalore",
  "bengaluru",
  "sydney",
  "melbourne",
  "tokyo",
  "tel aviv",
  "abu dhabi",
  "dubai",
  "são paulo",
  "sao paulo",
  "mexico city",
];

// Comprehensive US place-name set (~18.6k names), generated by scripts/build-us-cities.mjs
// from a maintained public dataset. Re-run that script to refresh. Used as a fallback tier
// so ANY US city (not just a hand-picked handful) is recognized — see isUsLocation below.
import usPlacesData from "./us-places.json";
const US_PLACES = new Set<string>(usPlacesData as string[]);

const SEGMENT_DELIMITERS = /[,\-/|()]/;

/** True if any comma/dash/slash/pipe/paren-delimited segment exactly matches a US place name. */
function hasUsPlaceSegment(lower: string): boolean {
  const segments = lower
    .split(SEGMENT_DELIMITERS)
    .map((s) => s.trim().replace(/\s+/g, " "))
    .filter(Boolean);
  return segments.some((seg) => US_PLACES.has(seg));
}

/**
 * Strict US-only classifier for freeform job-board location strings. Order matters:
 * country/region blocklist, then US signals (phrase/state/abbrev), then a non-US city
 * blocklist, THEN the full US place-name set, then bare "remote" — this is what correctly
 * separates "Dublin, OH" (US) from "Ireland - Dublin Office" (not US), and keeps "London"/
 * "Dublin" reading as non-US even though both are also real (much smaller) US place names.
 * Unknown/blank locations are treated as NOT confirmed US.
 */
export function isUsLocation(location: string | null): boolean {
  if (!location) return false;
  const lower = location.toLowerCase();

  if (matchesAny(lower, NON_US_COUNTRY_REGION_MARKERS)) return false;

  const hasUsPhrase = /(united states|\busa\b|u\.s\.a|u\.s\.|\bus\b)/i.test(lower);
  const hasUsState = matchesAny(lower, US_STATE_NAMES) || US_STATE_ABBR_RE.test(lower);
  if (hasUsPhrase || hasUsState) return true;

  if (matchesAny(lower, NON_US_CITY_MARKERS)) return false;

  if (hasUsPlaceSegment(lower)) return true;

  if (/\bremote\b/i.test(lower)) return true;

  return false;
}
